---
title: "p8105_hw2_sw3879"
author: "Siqing Wang"
date: "2023-09-27"
output: github_document
---

Importing libraries
```{r, message = FALSE}
library(tidyverse)
library(dplyr)
```
## Problem 1 

Read `pols-month.csv` into a dataframe and clean up data 

```{r, message = FALSE}
pols_month_df = 
  read_csv("data/pols-month.csv") |> 
  janitor::clean_names() |> 
  separate(mon, into = c("year", "month", "day"), sep = "-") |> 
  mutate(
    year = as.numeric(year),
    month = month.name[as.numeric(month)],
    president = ifelse(
      prez_gop > prez_dem, "gop", "dem"
    )
  ) |> 
  select(-day, -prez_gop, -prez_dem)
```

Cleaning data in `snp.csv`
```{r, message = FALSE}
snp_df = 
  read_csv("data/snp.csv") |> 
  janitor::clean_names() |> 
  mutate(
    date = format(as.Date(date, format = "%m/%d/%y"), "%Y/%m/%d")
  ) |> 
  separate(date, into = c("year", "month", "day"), sep = "/") |> 
  mutate(
    month = month.name[as.numeric(month)],
    year = as.numeric(year),
    year = ifelse(year > 2023, year - 100, year)
  ) |> 
  select(-day)
```

Pivoting `unemployment.csv` to long format
```{r, message = FALSE}
unemployment_df = 
  read_csv("data/unemployment.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment"
  ) |> 
  mutate(
    year = as.numeric(year),
    month = month.name[match(month, tolower(month.abb))]
  )
```

Merging the 3 datasets
```{r, message = FALSE}
result_df = left_join(pols_month_df,snp_df, by = c("year", "month")) |> 
  left_join(unemployment_df, by = c("year", "month"))
```

TO DO: INSERT DESCRIPTION

## Problem 2

Read in the Mr. Trash Wheel sheet 
```{r, message = FALSE}
trash_wheel_df = 
  readxl::read_excel("data/202207 Trash Wheel Collection Data.xlsx", 
                     sheet = "Mr. Trash Wheel", skip = 1) |> 
   janitor::clean_names() |>
  drop_na(dumpster) |> 
  select(-x15, -x16) |> 
  rename(homes_powered_old = homes_powered) |> 
  mutate(
    homes_powered = (weight_tons*500)/30,
    trash_wheel_name = "Mr. Trash Wheel"
  )
```

Read in professor trash wheel and gwynnda 
```{r, message = FALSE}
gwynnda_trash_wheel_df = 
  readxl::read_excel("data/202207 Trash Wheel Collection Data.xlsx", 
                     sheet = "Gwynnda Trash Wheel", skip = 1) |> 
   janitor::clean_names() |>
  drop_na(dumpster) |> 
  rename(homes_powered_old = homes_powered) |> 
  mutate(
    homes_powered = (weight_tons*500)/30,
    trash_wheel_name = "Gwynnda Trash Wheel"
  )

prof_trash_wheel_df = 
  readxl::read_excel("data/202207 Trash Wheel Collection Data.xlsx", 
                     sheet = "Professor Trash Wheel", skip = 1) |> 
   janitor::clean_names() |>
  drop_na(dumpster) |> 
  rename(homes_powered_old = homes_powered) |> 
  mutate(
    homes_powered = (weight_tons*500)/30,
    trash_wheel_name = "Professor Trash Wheel"
  )
```



